report:
  settings:
    page:
      size: Letter
      orientation: p
      margins: 15
    style:
      font_family: 'Helvetica'
      font_size: 10
      font_color: [0, 0, 0]
  header:
    1:
      text:
        field: company_name
        margin: 30
        align: left
        style:
          font_size: 11
          font_weight: B
    2:
      text:
        field: company_rif
        margin: 30
        align: left
        style:
          font_size: 10
    3:
      image:
        field: company_logo
        width: 20
        height: 20
        x: 20
        y: 12
    4:
      text:
        field: company_address
        margin: 30
        align: left
        style:
          font_size: 10
    5:
      breakline:
    6:
      pagenum:
        pattern: "Pag. <PAGE>"
        align: right
  body:
    1:
      text:
        label: "Num. Batch: "
        align: right
        width: 120
        breakline: 0
        style:
          font_weight: B
    2:
      text:
        field: batch
        align: left
        width: 50
    3:
      text:
        label: "Orden: "
        align: right
        width: 120
        breakline: 0
        style:
          font_weight: B
    4:
      text:
        field: order
        align: left
        width: 50
    5:
      text:
        label: "Receta: "
        align: right
        width: 120
        breakline: 0
        style:
          font_weight: B
    6:
      text:
        field: recipe
        align: left
        width: 50
    7:
      text:
        label: "Inicio: "
        align: right
        width: 120
        breakline: 0
        style:
          font_weight: B
    8:
      text:
        field: start_date
        align: left
        width: 50
    9:
      text:
        label: "Final: "
        align: right
        width: 120
        breakline: 0
        style:
          font_weight: B
    10:
      text:
        field: end_date
        align: left
        width: 50
    11:
      breakline:
    12:
      text:
        field: title
        align: center
        style:
          font_size: 12
          font_weight: B
    13:
      table:
        field: results
        heading:
          align: left
          style:
            font_weight: B
            bg_color: [220, 220, 220]
        totalization:
          precision: 2
          label: Totales
          align: right
          border: T
          style:
            font_weight: B
        columns:
          1:
           code:
              label: Codigo
              align: left
              width: 20
          2:
            ingredient:
              label: Materia Prima
              align: left
              width: 45
          3:
            std_kg:
              label: Cant. Est.
              align: right
              width: 25
              unit: Kg
              totalize: true
              precision: 2
          4:
            real_kg:
              label: Cant. Real
              align: right
              unit: Kg
              width: 25
              totalize: true
              precision: 2
          5:
            var_kg:
              label: Var Kg
              align: right
              unit: Kg
              width: 25
              totalize: true
              precision: 2
          6:
            var_perc:
              label: Var %
              align: center
              unit: '%'
              width: 20
              precision: 1
              perc_totalize: true
              perc_num: 'var_kg'
              perc_dem: 'std_kg'
          7:
            hopper:
              label: Tolva
              align: right
              width: 15
          8:
            lot:
              label: Lote
              align: right
              width: 15
    14:
      breakline:
  footer:
    1:
      text:
        field: footer
        align: center
        style:
          font_size: 8
          font_color: [80, 80, 80]
