report:
  settings:
    page:
      size: Letter
      orientation: L
      margins: 10
    style:
      font_family: 'Helvetica'
      font_size: 10
      font_color: [0, 0, 0]
  header:
    1:
      text:
        field: company_name
        margin: 30
        align: left
        style:
          font_size: 11
          font_weight: B
    2:
      text:
        field: company_rif
        margin: 30
        align: left
        style:
          font_size: 10
    3:
      image:
        field: company_logo
        width: 20
        height: 20
        x: 20
        y: 12
    4:
      text:
        field: company_address
        margin: 30
        align: left
        style:
          font_size: 10
    5:
      breakline:
    6:
      pagenum:
        pattern: "Pag. <PAGE>"
        align: right
  body:
    1:
      text:
        label: "Desde: "
        align: right
        width: 200
        breakline: 0
        style:
          font_weight: B
    2:
      text:
        field: since
        align: left
        width: 80
    3:
      text:
        label: "Hasta: "
        align: right
        width: 200
        breakline: 0
        style:
          font_weight: B
    4:
      text:
        field: until
        align: left
        width: 50
    5:
      breakline:
    6:
      text:
        field: title
        align: center
        style:
          font_size: 12
          font_weight: B
    7:
      table:
        field: results
        heading:
          align: left
          style:
            font_weight: B
            bg_color: [220, 220, 220]
        columns:
          1:
           code:
              label: Codigo
              align: left
              width: 40
          2:
            ingredient:
              label: Ingrediente
              align: left
              width: 65
          3:
            time:
              label: Fecha y hora
              align: center
              width: 40
          4:
            user:
              label: Usuario
              align: center
              width: 20
          5:
            type:
              label: Tipo
              align: center
              width: 15
          6:
            amount:
              label: Cantidad
              align: right
              unit: Kg
              width: 35
              precision: 2
          7:
            stock:
              label: Existencia
              align: right
              unit: Kg
              width: 35
              precision: 2
    8:
      breakline:
  footer:
    1:
      text:
        field: footer
        align: center
        style:
          font_size: 8
          font_color: [80, 80, 80]
