report:
  settings:
    page:
      size: Letter
      orientation: L
      margins: 10
    style:
      font_family: 'Helvetica'
      font_size: 10
      font_color: [0, 0, 0]
  header:
    1:
      text:
        field: company_name
        margin: 30
        align: left
        style:
          font_size: 11
          font_weight: B
    2:
      text:
        field: company_rif
        margin: 30
        align: left
        style:
          font_size: 10
    3:
      image:
        field: company_logo
        width: 20
        height: 20
        x: 20
        y: 12
    4:
      text:
        field: company_address
        margin: 30
        align: left
        style:
          font_size: 10
    5:
      breakline:
    6:
      pagenum:
        pattern: "Pag. <PAGE>"
        align: right
  body:
    1:
      text:
        label: "Desde: "
        align: right
        width: 240
        breakline: 0
        style:
          font_weight: B
    2:
      text:
        field: since
        align: left
        width: 50
    3:
      text:
        label: "Hasta: "
        align: right
        width: 240
        breakline: 0
        style:
          font_weight: B
    4:
      text:
        field: until
        align: left
        width: 50
    5:
      breakline:
    6:
      text:
        field: title
        align: center
        style:
          font_size: 12
          font_weight: B
    7:
      table:
        field: results
        heading:
          align: left
          style:
            font_weight: B
            bg_color: [220, 220, 220]
        totalization:
          precision: 2
          label: Totales
          align: right
          border: T
          style:
            font_weight: B
        columns:
          1:
           order :
              label: Orden
              align: left
              width: 20
          2:
            date:
              label: Fecha
              align: left
              width: 20
          3:
            recipe_name:
              label: Receta
              align: left
              width: 48
          4:
            average_tons_per_hour:
              label: Ton/Hrs
              align: right
              width: 20
              precision: 2
          5:
            average_batch_duration:
              label: Min/batch
              align: right
              width: 20
              precision: 2
          6:
            order_duration:
              label: Min
              align: right
              width: 15
              precision: 0
          7:
            real_batches:
              label: Batch
              align: right
              width: 10
          8:
            start_time:
              label: Inicio
              align: center
              width: 25
          9:
            end_time:
              label: Fin
              align: center
              width: 25
          10:
            total_standard:
              label: Total Est. (Kg)
              align: right
              width: 28
              totalize: true
              precision: 2
          11:
            total_real:
              label: Total Real (Kg)
              align: right
              width: 28
              totalize: true
              precision: 2
    8:
      breakline:
  footer:
    1:
      text:
        field: footer
        align: center
        style:
          font_size: 8
          font_color: [80, 80, 80]
