report:
  settings:
    page:
      size: 'Half Letter'
      orientation: P
      margins: 10
    style:
      font_family: 'Helvetica'
      font_size: 10
      font_color: [0, 0, 0]
  header:
    1:
      text:
        field: company_name
        margin: 30
        align: left
        style:
          font_size: 11
          font_weight: B
    2:
      text:
        field: company_rif
        margin: 30
        align: left
        style:
          font_size: 10
    3:
      image:
        field: company_logo
        width: 20
        height: 20
        x: 20
        y: 12
    4:
      text:
        field: company_address
        margin: 30
        align: left
        style:
          font_size: 10
    5:
      breakline:
    6:
      pagenum:
        pattern: "Pag. <PAGE>"
        align: right
  body:
    1:
      text:
        label: "Desde: "
        align: right
        width: 240
        breakline: 0
        style:
          font_weight: B
    2:
      text:
        field: since
        align: left
        width: 50
    3:
      text:
        label: "Hasta: "
        align: right
        width: 240
        breakline: 0
        style:
          font_weight: B
    4:
      text:
        field: until
        align: left
        width: 50
    5:
      breakline:
    6:
      text:
        field: title
        align: center
        style:
          font_size: 12
          font_weight: B
    7:
      table:
        field: results
        heading:
          align: left
          style:
            font_weight: B
            bg_color: [220, 220, 220]
        totalization:
          precision: 2
          label: Totales
          align: right
          border: T
          style:
            font_weight: B
        columns:
          1:
            date:
              label: Fecha
              align: left
              width: 25
          2:
           lot_code :
              label: Cod. Lote
              align: left
              width: 25
          3:
            content_code:
              label: Codigo Prod.
              align: left
              width: 30
          4:
            doc_number:
              label: Nro. Doc.
              align: left
              width: 25
          5:
            content_name:
              label: Nombre
              align: left
              width: 45
          6:
            amount:
              label: Cant. (Kg)
              align: right
              width: 30
              precision: 2
              totalize: true
          7:
            user_name:
              label: Usuario
              align: left
              width: 25
          8:
            comment:
              label: Comentario
              align: left
              width: 50
    8:
      breakline:
  footer:
    1:
      text:
        field: footer
        align: center
        style:
          font_size: 8
          font_color: [80, 80, 80]
