report:
  settings:
    page:
      size: Letter
      orientation: P
      margins: 10
    style:
      font_family: 'Helvetica'
      font_size: 10
      font_color: [0, 0, 0]
  header:
    1:
      text:
        field: company_name
        margin: 30
        align: left
        style:
          font_size: 11
          font_weight: B
    2:
      text:
        field: company_rif
        margin: 30
        align: left
        style:
          font_size: 10
    3:
      image:
        field: company_logo
        width: 20
        height: 20
        x: 20
        y: 12
    4:
      text:
        field: company_address
        margin: 30
        align: left
        style:
          font_size: 10
    5:
      breakline:
    6:
      pagenum:
        pattern: "Pag. <PAGE>"
        align: right
  body:
    1:
      text:
        label: "Fecha: "
        align: right
        width: 170
        breakline: 0
        style:
          font_weight: B
    2:
      text:
        field: date
        align: left
        width: 50
    3:
      breakline:
    4:
      text:
        field: title
        align: center
        style:
          font_size: 12
          font_weight: B
    5:
      table:
        field: results
        heading:
          align: left
          style:
            font_weight: B
            bg_color: [220, 220, 220]
        totalization:
          precision: 2
          label: Totales
          align: right
          border: T
          style:
            font_weight: B
        columns:
          1:
            code:
              label: Codigo
              align: left
              width: 30
          2:
            name:
              label: Nombre
              align: left
              width: 110
          3:
            stock:
              label: Existencia
              align: right
              unit: Kg
              width: 40
              totalize: true
              precision: 2
    6:
      breakline:
  footer:
    1:
      text:
        field: footer
        align: center
        style:
          font_size: 8
          font_color: [80, 80, 80]
