report:
  settings:
    page:
      size: Letter
      orientation: L
      margins: 10
    style:
      font_family: 'Helvetica'
      font_size: 10
      font_color: [0, 0, 0]
  header:
    1:
      text:
        field: company_name
        margin: 30
        align: left
        style:
          font_size: 11
          font_weight: B
    2:
      text:
        field: company_rif
        margin: 30
        align: left
        style:
          font_size: 10
    3:
      image:
        field: company_logo
        width: 20
        height: 20
        x: 20
        y: 12
    4:
      text:
        field: company_address
        margin: 30
        align: left
        style:
          font_size: 10
    5:
      breakline:
    6:
      pagenum:
        pattern: "Pag. <PAGE>"
        align: right
  body:
    1:
      text:
        label: "Desde: "
        align: right
        width: 170
        breakline: 0
        style:
          font_weight: B
    2:
      text:
        field: since
        align: left
        width: 50
    3:
      text:
        label: "Hasta: "
        align: right
        width: 170
        breakline: 0
        style:
          font_weight: B
    4:
      text:
        field: until
        align: left
        width: 50
    5:
      text:
        label: "Chofer: "
        align: right
        width: 170
        breakline: 0
        style:
          font_weight: B
    6:
      text:
        field: driver
        align: left
        width: 50
    7:
      breakline:
    8:
      text:
        field: title
        align: center
        style:
          font_size: 12
          font_weight: B
    9:
      table:
        field: table1
        heading:
          align: left
          style:
            font_weight: B
            bg_color: [220, 220, 220]
        totalization:
          precision: 2
          label: Total
          align: right
          border: T
          style:
            font_weight: B
        columns:
          1:
            number:
              label: Ticket
              align: left
              width: 20
          2:
            client:
              label: Cliente
              align: left
              width: 70
          3:
            content_name:
              label: Materia Prima
              align: left
              width: 70
          4:
            sacks:
              label: Sacos
              align: right
              width: 30
          5:
            sack_weight:
              label: Kg/Sacos
              align: right
              width: 30
          6:
            amount:
              label: Cantidad
              align: right
              unit: Kg
              width: 30
              totalize: true
              precision: 2
    10:
      breakline:
  footer:
    1:
      text:
        field: footer
        align: center
        style:
          font_size: 8
          font_color: [80, 80, 80]
