report:
  settings:
    page:
      size: Letter
      orientation: P
      margins: 20
    style:
      font_family: 'Helvetica'
      font_size: 10
      font_color: [0, 0, 0]
  header:
    1:
      text:
        field: company_name
        margin: 30
        align: left
        style:
          font_size: 11
          font_weight: B
    2:
      text:
        field: company_rif
        margin: 30
        align: left
        style:
          font_size: 10
    3:
      image:
        field: company_logo
        width: 20
        height: 20
        x: 20
        y: 12
    4:
      text:
        field: company_address
        margin: 30
        align: left
        style:
          font_size: 10
    5:
      breakline:
    6:
      pagenum:
        pattern: "Pag. <PAGE>"
        align: right
  body:
    1:
      text:
        label: "Orden: "
        align: right
        width: 120
        breakline: 0
        style:
          font_weight: B
    2:
      text:
        field: order
        align: left
        width: 50
    3:
      text:
        label: "Cliente: "
        align: right
        width: 120
        breakline: 0
        style:
          font_weight: B
    4:
      text:
        field: client
        align: left
        width: 50
    5:
      text:
        label: "Formula: "
        align: right
        width: 120
        breakline: 0
        style:
          font_weight: B
    6:
      text:
        field: recipe
        align: left
        width: 50
    7:
      text:
        label: "Version: "
        align: right
        width: 120
        breakline: 0
        style:
          font_weight: B
    8:
      text:
        field: version
        align: left
        width: 50
    9:
      text:
        label: "Prod. Term.: "
        align: right
        width: 120
        breakline: 0
        style:
          font_weight: B
    10:
      text:
        field: product
        align: left
        width: 50
    11:
      text:
        label: "Inicio: "
        align: right
        width: 120
        breakline: 0
        style:
          font_weight: B
    12:
      text:
        field: start_date
        align: left
        width: 50
    13:
      text:
        label: "Final: "
        align: right
        width: 120
        breakline: 0
        style:
          font_weight: B
    14:
      text:
        field: end_date
        align: left
        width: 50
    15:
      breakline:
    16:
      text:
        field: title
        align: center
        style:
          font_size: 12
          font_weight: B
    17:
      breakline:
    18:
      text:
        field: tabletitle
        align: left
        style:
          font_size: 10
          font_weight: B
    19:
      table:
        field: table
        heading:
          align: left
          style:
            font_weight: B
            bg_color: [220, 220, 220]
        columns:
          1:
           name:
              label: Caracteristica
              align: left
              width: 40
          2:
            value:
              label: Valor
              align: left
              width: 50
          3:
            unit:
              label: Unidad
              align: center
              width: 20
          4:
            min:
              label: Minimo
              align: center
              width: 35
          5:
            max:
              label: Maximo
              align: center
              width: 35
    20:
      breakline:
  footer:
    1:
      text:
        field: footer
        align: center
        style:
          font_size: 8
          font_color: [80, 80, 80]
